---
title: "R Shiny Aficianado"
---


***
  >Hi, my name is Ben Gonzalez and I am an avid R-Shiny developer. I began learning R while in graduate school at Saint Louis University, home of the Billiken's, and loved what I was doing. After many sleepless nights in the beginning I gained a knack for using R and moved on to Shiny App development. While at SLU I needed to come up with my final project, and I discovered Text Analysis in computer science. Having a Masters degree in Communication as well as in Adult &amp; Higher Education I saw a need for such applications. Such began my discovery of text analysis and how powerful it is. I began developing my first full blown Shiny application with all of the bells and whistles. Utilizing R and Shiny I was able to remove the technical side of text analysis and make it available to the lay user. Thus, allowing a diverse array of individual's the ability to perform text analysis without any of the necessary technical background for things like R and Shiny.

***